### ISSUE TITLE
more potential formats listed by @mamund

### ISSUE THREAD

**Issue by dret** [dret/hypermedia#6]
@mamund has another list of hypermedia formats listed at http://amundsen.com/hypermedia/; the list contains: X/HTML, Atom, VoiceXML, CCXML, SMIL, SVG, Turtle, Notation 3, TriX, TriG, RDF/XML, SensorML, CSS, text/uri-list, Sitemap XML
the various RDF serializations probably could be safely collapsed into just describing RDF (but then again, that's not actually a hypermedia format, per hyperpedia's definition).

**Comment by dret** [comment]
adding home documents: https://github.com/dret/hyperpedia/commit/abb52c4aed2971755c9da218498aa9013e9ddef3

**Comment by mamund** [comment]
The list i created for [Hypermedia Types](http://amundsen.com/hypermedia/) page was focused on identifying _affordances_ within registered formats. I was not (at that time) focused on granting the "hypermedia type" status to selected formats that met some bar or criteria. 

Whether you want to include some/all of the formats listed there in your the hyperpedia is likely a different set of decision points. And, the notion of collapsing one or more registered formats into a single entry is also a decision that relates more to your goals here than they do to the goals I had in mind when creating the list for H-Factor review.

Now, _personally_, I'd include here any format that exhibits one or more of the [H-Factors](http://amundsen.com/hypermedia/hfactor/) and I would _not_ conflate multiple formats into a single entry. But I may not understand your aims here.

**Comment by dret** [comment]
i completely agree that the very definition of a hypermedia format should be that it has some hypemedia-ish properties. for hyperpedia, that would mean it implements at least one of the concepts described at https://github.com/dret/hyperpedia/blob/master/concepts.md (except for target identification i guess because that's just about _being addressable_ and not actually doing something in addition to that, so it's a very low threshold that applies to anything that has a URI on the web.)
however, i still don't understand why you would want to separately list all RDF serializations which are all just different ways to represent the same concepts. that to me would be the same as requiring EXI to be listed in addition to XML, because they both are different representations (of the same underlying XML model).

**Comment by mamund** [comment]
I will address the notion of a "definition of hypermedia" here first.

DEFINITION OF HYPERMEDIA
if you want to created a definition of a hypermedia format, I think you
need a single sentence or phrase (e.g. a dictionary entry). I attempted
this as follows:

"Hypermedia Types are MIME media types that contain native hyper-linking
semantics that induce application flow. For example, HTML is a hypermedia
type; XML is not."[1]

This could be improved ("induce application flow" is vague and weak).

Your "it implements at least one of the concepts described at
https://github.com/dret/hyperpedia/blob/master/concepts.md" is a good
start, but also not sharp enough, IMO. For example, "Readable Label" is one
of the items in your list and having that alone is not an acceptable
definition of a media type. In fact, IMO, none of the single items in your
list would suffice to define a hypermedia format (or type).

I suspect something that uses the H-Factor[2] list (or some improved
derivative or simile of that list) would be sufficient. For example:

"Hypermedia Formats MUST exhibit one or more of the Link Factors (LO, LE,
LT, LI, LN) in the H-Factor list within responses"

Again, I think this H-Factor list may be too loose to contain a _good_
definition of a hypermedia format.

Another possibility is to rely on the Hypermedia Aspects[3] of
- Safety
- Idempotence
- Transclusion
- Mutability

(or some better list -- such that)

"Hypermedia Formats MUST exhibit ALL of the Hypermedia Aspects within the
message"

Again, I think this H-Factor list may be too loose to contain a _good_
definition of a hypermedia format.

Anyway, solving this problem SHOULD make it easy to know which
IANA-registered formats to include in any list of hypermedia types.

As for "grouping" formats or collapsing them in the list presumably because
they are "the same" -- this would be, IMO, an easy call if you could show
that multiple IANA-reg'd formats have the exact same hypermedia signature.
This may also, BTW, mean some formats are not listed like HAL and some HAL
copy since they both have the same "hypermedia signature"

[1] http://amundsen.com/hypermedia/
[2] http://amundsen.com/hypermedia/hfactor/
[3]
http://www.w3.org/2011/10/integration-workshop/p/hypermedia-oriented-design.pdf

**Comment by dret** [comment]
On 2015-08-26 18:29 , Mike Amundsen wrote:

> I will address the notion of a "definition of hypermedia" here first.
> DEFINITION OF HYPERMEDIA
> if you want to created a definition of a hypermedia format, I think you
> need a single sentence or phrase (e.g. a dictionary entry). I attempted
> this as follows:
> "Hypermedia Types are MIME media types that contain native hyper-linking
> semantics that induce application flow. For example, HTML is a hypermedia
> type; XML is not."[1]
> This could be improved ("induce application flow" is vague and weak).

actually, i think it would be more useful to start with "hypermedia 
applications", because that's what's the actual product. those can be 
based on one or more "formats", and then this also very naturally makes 
clear that while JPG in itself might not be useful format in itself, 
when used correctly (i.e., served at stable and discoverable URIs), it 
can become an integral part of an hypermedia application.

i hope this does not come across as being pedantic, but i think this is 
what matters most. http://dret.github.io/webdata/ is trying to make this 
point as well, saying that the first step is to be addressable. then of 
course there's more, but even that first step turn something into a 
useful resource in an hypermedia application.

> Your "it implements at least one of the concepts described at
> https://github.com/dret/hyperpedia/blob/master/concepts.md" is a good
> start, but also not sharp enough, IMO. For example, "Readable Label" is one
> of the items in your list and having that alone is not an acceptable
> definition of a media type. In fact, IMO, none of the single items in your
> list would suffice to define a hypermedia format (or type).

i'd argue that some would, such as having outgoing links. if those are 
typed in one way or another, then that's good enough. but i certainly 
agree that this list could be improved, and that's my goal.

> I suspect something that uses the H-Factor[2] list (or some improved
> derivative or simile of that list) would be sufficient. For example:
> "Hypermedia Formats MUST exhibit one or more of the Link Factors (LO, LE,
> LT, LI, LN) in the H-Factor list within responses"

personally, i never quite understood the way in which those factors are 
structured, and hyperpedia's concepts are an attempt to have a better 
separation of concerns in such a set of criteria.

most of the things that seem to distinguish the h-factors probably 
factors into what hyperpedia calls "target resource hints" and 
"traversal hints", and at least now these are less finely defined than 
the h-factors.

other hypermedia concepts do not seem to be covered by h-factors at all, 
such as link topology and how link relation types are encoded.

> Again, I think this H-Factor list may be too loose to contain a _good_
> definition of a hypermedia format.

like with many relatively fuzzy concepts, i think it's hard to find a 
good balance between being narrowly defined, without excluding too many 
things that probably should also be covered, but may not be such a great 
fit for a more narrow definition.

> Another possibility is to rely on the Hypermedia Aspects[3] of
> - Safety
> - Idempotence
> - Transclusion
> - Mutability
>   (or some better list -- such that)

to me, this now really is venturing too far into REST and similar 
things. for me, hypermedia is not so much about these RESTish things, 
but more just the HATEOAS part of it: the ability to link resources 
together so that meaningful applications can be built.

it would be great to maybe extend such a more general definition of 
hypermedia with a more REST-focused perspective on the things you 
mention above, but that should be done separately.

for example, W3C's DWBP group is struggling mightily with simply giving 
good guidelines about the fact that for publishing data on the web, it 
should be webby, in which case being hypermedia is a core requirement. 
they don't really care so much about the more state/workflow-focused 
things you're mentioning above, but they certainly could use a good 
definition of hypermedia that they could point publishers to.

> Anyway, solving this problem SHOULD make it easy to know which
> IANA-registered formats to include in any list of hypermedia types.

i think in an ideal world you'd end up with a matrix. all types as rows, 
all concepts as columns. some formats satisfy all concepts, others only 
some (and all of them, when made available on the web, of course are 
"addressable" and thus satisfy that simple criterion). it would then be 
up to the reader of the matrix to decide which columns he thinks are 
necessary to be a "real" hypermedia format.

and of course, if you wanted to be really thorough, each checkmark would 
an explanation of how exactly that format implements that concept, and 
there's probably always a spectrum of "just barely" to "really well".

> As for "grouping" formats or collapsing them in the list presumably because
> they are "the same" -- this would be, IMO, an easy call if you could show
> that multiple IANA-reg'd formats have the exact same hypermedia signature.

i don't think so. only because two formats satisfy the same concepts 
doesn't turn them into the same thing. they just do the hypermedia side 
of things in the same way.

but of course if you then looked at the rows of all the different RDF 
serializations, they would all have the same checkmarks, because it 
really does not matter how you serialize RDF, it will always be the same 
model that is being represented.

**Comment by dret** [comment]
mentioning this here because it's an open issue already: https://github.com/dret/hyperpedia/issues/3 asks to clarify how hyperpedia concepts and h-factors relate.

**Comment by mamund** [comment]
lots here and i'll just address Aspects first.

<snip>
to me, this now really is venturing too far into REST and similar
things.
</snip>
these are not REST things and never appear in the dissertation. the first
two are called specifically in HTTP and also exist in other formats like
CoAP and FTP (for a start). In fact, _every_ protocol deals with both of
these issues whether implicitly or explicitly.  the second two appear in
HTML (tho not called out by these names) and transclusion is "all over" the
XLink docs.

defining 'hypermedia application' is not something i am interested in doing
but would love to se it.
if H-Factors are not your thing no matter. I am not interested in pressing
that these should be used here.

<snip>
i'd argue that some would,
</snip>
yes, _some_ that's my point. saying "it implements one of..." is not
enough. saying "it implements outgoing links" is much better though I would
not may _outgoing_ a requirement.

i have nothing else to add regarding your POV on how to treat registered
REF formats.

cheers.

mamund
+1.859.757.1449
skype: mca.amundsen
http://amundsen.com/blog/
http://twitter.com/mamund
https://github.com/mamund
http://linkedin.com/in/mamund
